apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: app
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP