apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: app
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: milanjuneja7/api-gateway:latest
          ports:
            - containerPort: 9000