apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: app
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP